#!/usr/bin/env bash

DOCKER_USER=minbull
IMAGE_PREFIX=ai_

RUNTIME_VERSION=1.0.1
RUNTIME_IMAGE=runtime
RUNTIME_IMAGE_FULL="$IMAGE_PREFIX$RUNTIME_IMAGE"

BASE_IMAGE_VERSION=1.0.0
BASE_IMAGE=base
BASE_IMAGE_FULL="$IMAGE_PREFIX$BASE_IMAGE"

AI_LIB_IMAGE_VERSION=1.0.1
AI_LIB_IMAGE=runtime_lib
AI_LIB_IMAGE_FULL="$IMAGE_PREFIX$AI_LIB_IMAGE"
