.PHONY: build up start stop down status workspace

build:
	docker-compose build runtime

workspace:
	docker-compose build workspace

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps