version: '3'

services:
    nginx:
      build:
        context: ./nginx
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        #指定本地路径
        - "/easy_ai:/usr/share/nginx/files"   
      ports:
        - "8080:80"
      tty: true