version: '3'

services:
    nginx:
      build:
        context: ./nginx
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d 
        - "/easy_ai:/usr/share/nginx/files"  
      ports:
        - "8080:80"
      tty: true